# Site settings
title: Stata econpucp
tag_text: STATA ECONPUCP GUÍA Y REPOSITORIO DE STATA PARA LA INVESTIGACIÓN ECONÓMICA
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
